name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Webview APK
        uses: nttld/setup-ndk@v1 

      - name: Generate APK
        uses: hey947/pwa-to-apk@v1.1
        with:
          app-name: "Android-col-window"
          package-name: "com.earthvoxels.coolwindow"
          url: "https://cool-window.netlify.app" 
          orientation: "landscape"
          icon: "icon.png"
