name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build APK
        uses: pmarati/webview-apk-action@main
        with:
          app_name: "Android-col-window"
          app_id: "com.earthvoxels.coolwindow"
          url: "https://cool-window.netlify.app"
          orientation: "landscape"
